### create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"wang8119@gmail.com",
    "password":"wang8119@gmail.com"
}

### find a particular user with a given id
GET http://localhost:3000/auth/1

### find all user with a given email
GET http://localhost:3000/auth?email=wang8119@gmail.com

